[site]: crossvalidated
[post_id]: 376464
[parent_id]: 
[tags]: 
convolutional autoencoder on an odd size image

I am trying to apply convolutional autoencdeor on a odd size image. Below is the code: from keras.layers import Input, Dense, Conv2D, MaxPooling2D, UpSampling2D from keras.models import Model # from keras import backend as K input_img = Input(shape=(91, 91, 1)) # adapt this if using `channels_first` image data format x = Conv2D(16, (3, 3), activation='relu', padding='same')(input_img) x = MaxPooling2D((2, 2), padding='same')(x) x = Conv2D(8, (3, 3), activation='relu', padding='same')(x) x = MaxPooling2D((2, 2), padding='same')(x) x = Conv2D(8, (3, 3), activation='relu', padding='same')(x) encoded = MaxPooling2D((2, 2), padding='same')(x) # at this point the representation is (4, 4, 8) i.e. 128-dimensional x = Conv2D(8, (3, 3), activation='relu', padding='same')(encoded) x = UpSampling2D((2, 2))(x) x = Conv2D(8, (3, 3), activation='relu', padding='same')(x) x = UpSampling2D((2, 2))(x) x = Conv2D(16, (3, 3), activation='relu')(x) x = UpSampling2D((2, 2))(x) decoded = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(x) autoencoder = Model(input_img, decoded) autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy') autoencoder.summary() which gives the following: Layer (type) Output Shape Param # ================================================================= input_22 (InputLayer) (None, 91, 91, 1) 0 _________________________________________________________________ conv2d_145 (Conv2D) (None, 91, 91, 16) 160 _________________________________________________________________ max_pooling2d_64 (MaxPooling (None, 46, 46, 16) 0 _________________________________________________________________ conv2d_146 (Conv2D) (None, 46, 46, 8) 1160 _________________________________________________________________ max_pooling2d_65 (MaxPooling (None, 23, 23, 8) 0 _________________________________________________________________ conv2d_147 (Conv2D) (None, 23, 23, 8) 584 _________________________________________________________________ max_pooling2d_66 (MaxPooling (None, 12, 12, 8) 0 _________________________________________________________________ conv2d_148 (Conv2D) (None, 12, 12, 8) 584 _________________________________________________________________ up_sampling2d_64 (UpSampling (None, 24, 24, 8) 0 _________________________________________________________________ conv2d_149 (Conv2D) (None, 24, 24, 8) 584 _________________________________________________________________ up_sampling2d_65 (UpSampling (None, 48, 48, 8) 0 _________________________________________________________________ conv2d_150 (Conv2D) (None, 46, 46, 16) 1168 _________________________________________________________________ up_sampling2d_66 (UpSampling (None, 92, 92, 16) 0 _________________________________________________________________ conv2d_151 (Conv2D) (None, 92, 92, 1) 145 ================================================================= Total params: 4,385 Trainable params: 4,385 Non-trainable params: 0 We can see that the input and output are not of the same size. So when i do the autoencoder.fit , it throws the error that ValueError: Error when checking target: expected conv2d_7 to have shape (92, 92, 1) but got array with shape (91, 91, 1) . What to do to rectify this?
