[site]: datascience
[post_id]: 14718
[parent_id]: 
[tags]: 
Keras Import Error

While importing keras (from keras.models import Sequential), I am getting the following error: Traceback (most recent call last): File "/home/afzal/Deep cnn/cnn_deeplearningpgm/keras_cnn_new3.py", line 2, in import keras File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/__init__.py", line 2, in from . import backend File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/backend/__init__.py", line 29, in _config = json.load(open(_config_path)) File "/usr/lib/python2.7/json/__init__.py", line 291, in load **kw) File "/usr/lib/python2.7/json/__init__.py", line 339, in loads return _default_decoder.decode(s) File "/usr/lib/python2.7/json/decoder.py", line 364, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode obj, end = self.scan_once(s, idx) ValueError: Expecting object: line 5 column 25 (char 108) I have installed theano. Could anyone help me solve this?
