[site]: stackoverflow
[post_id]: 2072767
[parent_id]: 2072459
[tags]: 
Hard to tell without knowing what the code for the original throw is doing. It is possible that there are outstanding forms events that get processed as part of the app shutdown that ends up re-invoking the original code fragment. It could also be a virtual function on your application class that gets invoked during shutdown. You should be able to just print the stack trace from your catch handler to figure it out though.
