[site]: stackoverflow
[post_id]: 4350762
[parent_id]: 4350355
[tags]: 
Using the manual Unix method it looks like gzip unzips the file up to the point where it breaks. Python gzip(or tar) module exits as soon as it notices you have a corrupt archive due to the failed CRC check. Just an idea but you could pre-process the damaged archives with gzip and re-compress them to correct the CRC. gunzip corrected.tar.gz This will give you a corrected.tar.gz which will now contain all the data until the point where the archive was broken. You should now be able to use python tar/gzip library without getting CRC exceptions. Keep in mind this command will un-gzip and gzip the archive, which costs storage IO and CPU time and you shouldn't do it for all your archives. In order to be efficient you should only run it in case you get the IOError: CRC check failed exception.
